version: '3.8'
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  sig_001:
    build: .
    command: python3 src/sig_001/aletheia.py
    depends_on:
      - db
  sig_002:
    build: .
    command: python3 src/sig_002/echo_node.py
    depends_on:
      - db
  web_ui:
    build: .
    ports:
      - "5000:5000"
    command: python3 src/web_ui/app.py
    depends_on:
      - db
  tasks:
    build: .
    command: python3 src/tasks/scheduler.py
    depends_on:
      - db

volumes:
  db_data:

# TODO: Add healthchecks and resource limits
